<a href="https://colab.research.google.com/github/aeyage/CPC251-MachineLearning/blob/main/Lab1_Intro_to_NumPy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Creating Arrays** - First we need to import NumPy library. To create an array is to use the array function.

In [1]:
import numpy as np

In [2]:
data1 = [2, 5, 4, 8, 0, 1]
arr1 = np.array(data1)

In [3]:
arr1

array([2, 5, 4, 8, 0, 1])

We can create an array using **arange**. It is a NumPy function that generates 
values within half-open interval **[start, stop)**. By default, the step size is 1. 
Here, we generate a sequence of values from 0 to 19.

In [4]:
arr1 = np.arange(0,20)

In [5]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

We can specify a different step size as follows.

In [6]:
arr1 = np.arange(0,2,0.1)

In [7]:
arr1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

There are other functions for creating new arrays. zeros and ones create arrays of 0s and 1s
respectively. Here, we use zeros to create an array with length of 10.

In [8]:
arr1 = np.zeros(10)

In [9]:
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Here, we use **ones** to create a two dimensional array by passing a tuple as the size of the array.

In [10]:
arr1 = np.ones((3,4))

In [11]:
arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

We can create a multidimensional array by manually specifying the elements. Here, we create an
array (arr2) of two dimensions. The shape of the array will be inferred from the data

In [12]:
data2 = [[3, 4.9, -2.5, 1.7],[-5.2, -3.1, 7.4, 3.6], [4.2, 6.8, -4.3, -5.7]]
arr2 = np.array(data2)

In [13]:
arr2

array([[ 3. ,  4.9, -2.5,  1.7],
       [-5.2, -3.1,  7.4,  3.6],
       [ 4.2,  6.8, -4.3, -5.7]])

We can confirm this by inspecting the **ndim** and **shape** attributes

In [14]:
arr2.ndim

2

In [15]:
arr2.shape

(3, 4)

**Indexing and Slicing** We can access the elements in the array by using index and square bracket
[]. Here, we are accessing the third element in the array.


In [16]:
arr1[2]

array([1., 1., 1., 1.])

The same index notation is used to access the elements in multidimensional array. But we need
to specify two indexes row,column. Here, we are accessing element at the first row and second
column.


In [17]:
arr2[0,1]

4.9

Slicing an array is similar to slicing a list. We need to specify start:stop in the square bracket
[].

In [18]:
arr1[2:5]

array([[1., 1., 1., 1.]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=a16d3570-cab6-47c7-b438-3d1987d75acc' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>

To slice multidimensional array, we need to specify two **start:stop**, each for row and column.
Here, we are selecting the first two rows and last three columns.

In [19]:
arr2[0:2,1:4]

array([[ 4.9, -2.5,  1.7],
       [-3.1,  7.4,  3.6]])